

export const multiCategoryData = [
    {
        id: "1",
        title: "Fruits & Vegetables",
        products: [
            {
                id: "101",
                name: "Apple",
                price: 120,
                cutPrice: 150,
                offer: "₹30",
                qty: "1 kg",
                tag: "Fresh Fruit",
                rating: "4.6 (12.3k)",
                image: require("../../assets/fruits&vegies/apple.jpeg"),
            },
            {
                id: "102",
                name: "Banana",
                price: 40,
                cutPrice: 55,
                offer: "₹15",
                qty: "1 dozen",
                tag: "Fresh Fruit",
                rating: "4.4 (9.1k)",
                image: require("../../assets/fruits&vegies/banana.jpeg"),
            },
            {
                id: "103",
                name: "Orange",
                price: 90,
                cutPrice: 120,
                offer: "₹30",
                qty: "1 kg",
                tag: "Citrus Fruit",
                rating: "4.5 (6.8k)",
                image: require("../../assets/fruits&vegies/orange.jpeg"),
            },
            {
                id: "104",
                name: "Strawberry",
                price: 250,
                cutPrice: 320,
                offer: "₹70",
                qty: "1 box (500g)",
                tag: "Fresh Fruit",
                rating: "4.8 (22.1k)",
                image: require("../../assets/fruits&vegies/strawberry.jpeg"),
            },
            {
                id: "105",
                name: "Grapes",
                price: 110,
                cutPrice: 150,
                offer: "₹40",
                qty: "1 kg",
                tag: "Fresh Fruit",
                rating: "4.5 (11.4k)",
                image: require("../../assets/fruits&vegies/grapes.jpeg"),
            },


            {
                id: "106",
                name: "Potato",
                price: 30,
                cutPrice: 40,
                offer: "₹10",
                qty: "1 kg",
                tag: "Fresh Veg",
                rating: "4.2 (8.9k)",
                image: require("../../assets/fruits&vegies/potato.jpeg"),
            },
            {
                id: "107",
                name: "Tomato",
                price: 28,
                cutPrice: 40,
                offer: "₹12",
                qty: "1 kg",
                tag: "Fresh Veg",
                rating: "4.3 (7.5k)",
                image: require("../../assets/fruits&vegies/tomato.jpeg"),
            },
            {
                id: "108",
                name: "Carrot",
                price: 50,
                cutPrice: 70,
                offer: "₹20",
                qty: "1 kg",
                tag: "Root Veg",
                rating: "4.6 (5.2k)",
                image: require("../../assets/fruits&vegies/carrot.jpeg"),
            },
            {
                id: "109",
                name: "Broccoli",
                price: 80,
                cutPrice: 110,
                offer: "₹30",
                qty: "500 g",
                tag: "Healthy Veg",
                rating: "4.7 (4.8k)",
                image: require("../../assets/fruits&vegies/broccoli.jpeg"),
            },
            {
                id: "110",
                name: "Onion",
                price: 35,
                cutPrice: 45,
                offer: "₹10",
                qty: "1 kg",
                tag: "Fresh Veg",
                rating: "4.3 (10.1k)",
                image: require("../../assets/fruits&vegies/onion.jpeg"),
            },
            {
                id: "103",
                name: "Orange",
                price: 90,
                cutPrice: 120,
                offer: "₹30",
                qty: "1 kg",
                tag: "Citrus Fruit",
                rating: "4.5 (6.8k)",
                image: require("../../assets/fruits&vegies/orange.jpeg"),
            },
            {
                id: "104",
                name: "Strawberry",
                price: 250,
                cutPrice: 320,
                offer: "₹70",
                qty: "1 box (500g)",
                tag: "Fresh Fruit",
                rating: "4.8 (22.1k)",
                image: require("../../assets/fruits&vegies/strawberry.jpeg"),
            },
            {
                id: "101",
                name: "Apple",
                price: 120,
                cutPrice: 150,
                offer: "₹30",
                qty: "1 kg",
                tag: "Fresh Fruit",
                rating: "4.6 (12.3k)",
                image: require("../../assets/fruits&vegies/apple.jpeg"),
            },
            {
                id: "102",
                name: "Banana",
                price: 40,
                cutPrice: 55,
                offer: "₹15",
                qty: "1 dozen",
                tag: "Fresh Fruit",
                rating: "4.4 (9.1k)",
                image: require("../../assets/fruits&vegies/banana.jpeg"),
            },
            {
                id: "103",
                name: "Orange",
                price: 90,
                cutPrice: 120,
                offer: "₹30",
                qty: "1 kg",
                tag: "Citrus Fruit",
                rating: "4.5 (6.8k)",
                image: require("../../assets/fruits&vegies/orange.jpeg"),
            },
        ],

    },
    {
        id: "2",
        title: "Dairy,Bread & Eggs",
        products: [
            {
                id: "211",
                name: "Amul Milk",
                price: 32,
                cutPrice: 38,
                offer: "₹6",
                qty: "500 ml",
                tag: "Fresh Dairy",
                rating: "4.7 (21.3k)",
                image: require("../../assets/dairy products/milk.jpeg"),

            },
            {
                id: "212",
                name: "Amul Butter",
                price: 52,
                cutPrice: 65,
                offer: "₹13",
                qty: "100 g",
                tag: "Dairy Product",
                rating: "4.8 (15.2k)",
                image: require("../../assets/dairy products/butter.jpeg"),
            },
            {
                id: "213",
                name: "Curd (Dahi)",
                price: 45,
                cutPrice: 55,
                offer: "₹10",
                qty: "500 g",
                tag: "Fresh Dairy",
                rating: "4.6 (9.8k)",
                image: require("../../assets/dairy products/curd.jpeg"),
            },
            {
                id: "214",
                name: "Paneer",
                price: 85,
                cutPrice: 110,
                offer: "₹25",
                qty: "200 g",
                tag: "Dairy Product",
                rating: "4.7 (12.1k)",
                image: require("../../assets/dairy products/paneer.jpeg"),
            },
            {
                id: "215",
                name: "Cheddar Cheese",
                price: 140,
                cutPrice: 180,
                offer: "₹40",
                qty: "200 g",
                tag: "Cheese",
                rating: "4.8 (6.3k)",
                image: require("../../assets/dairy products/cheese.jpeg"),
            },
            {
                id: "213",
                name: "Curd (Dahi)",
                price: 45,
                cutPrice: 55,
                offer: "₹10",
                qty: "500 g",
                tag: "Fresh Dairy",
                rating: "4.6 (9.8k)",
                image: require("../../assets/dairy products/curd.jpeg"),
            },

            // Bread
            {
                id: "216",
                name: "Wheat Bread",
                price: 38,
                cutPrice: 45,
                offer: "₹7",
                qty: "400 g loaf",
                tag: "Bakery",
                rating: "4.5 (5.1k)",
                image: require("../../assets/dairy products/wheatbread.jpeg"),
            },
            {
                id: "217",
                name: "White Bread",
                price: 36,
                cutPrice: 42,
                offer: "₹6",
                qty: "400 g loaf",
                tag: "Bakery",
                rating: "4.4 (4.3k)",
                image: require("../../assets/dairy products/whiteBread.jpeg"),
            },
            {
                id: "218",
                name: "Brown Bread",
                price: 40,
                cutPrice: 48,
                offer: "₹8",
                qty: "400 g loaf",
                tag: "Healthy Bakery",
                rating: "4.6 (3.9k)",
                image: require("../../assets/dairy products/brownBread.jpeg"),
            },

            // Eggs
            {
                id: "219",
                name: "Eggs (Regular)",
                price: 65,
                cutPrice: 80,
                offer: "₹15",
                qty: "12 pieces",
                tag: "Fresh Eggs",
                rating: "4.7 (25.8k)",
                image: require("../../assets/dairy products/eggs.jpeg"),
            },
            {
                id: "220",
                name: "Brown Eggs",
                price: 75,
                cutPrice: 95,
                offer: "₹20",
                qty: "12 pieces",
                tag: "Protein Rich",
                rating: "4.8 (13.4k)",
                image: require("../../assets/dairy products/brownEggs.jpeg"),
            },
            {
                id: "221",
                name: "Organic Eggs",
                price: 110,
                cutPrice: 135,
                offer: "₹25",
                qty: "6 pieces",
                tag: "Organic",
                rating: "4.9 (5.2k)",
                image: require("../../assets/dairy products/organiceggs.jpeg"),
            }.cutPrice,
            {
                id: "211",
                name: "Amul Milk",
                price: 32,
                cutPrice: 38,
                offer: "₹6",
                qty: "500 ml",
                tag: "Fresh Dairy",
                rating: "4.7 (21.3k)",
                image: require("../../assets/dairy products/milk.jpeg"),

            },
            {
                id: "212",
                name: "Amul Butter",
                price: 52,
                cutPrice: 65,
                offer: "₹13",
                qty: "100 g",
                tag: "Dairy Product",
                rating: "4.8 (15.2k)",
                image: require("../../assets/dairy products/butter.jpeg"),
            },
            {
                id: "213",
                name: "Curd (Dahi)",
                price: 45,
                cutPrice: 55,
                offer: "₹10",
                qty: "500 g",
                tag: "Fresh Dairy",
                rating: "4.6 (9.8k)",
                image: require("../../assets/dairy products/curd.jpeg"),
            },
        ]

    },

    {
        id: "3",
        title: "Packaged Snacks",
        products: [
            {
                id: "301",
                name: "Potato Chips",
                price: 35,
                cutPrice: 50,
                offer: "₹15",
                qty: "1 pack (100g)",
                tag: "Snacks",
                rating: "4.3 (12.1k)",
                image: require("../../assets/package snanks/chips.jpeg"),
            },
            {
                id: "302",
                name: "Salted Peanuts",
                price: 25,
                cutPrice: 35,
                offer: "₹10",
                qty: "1 pack",
                tag: "Snacks",
                rating: "4.1 (6.5k)",
                image: require("../../assets/package snanks/peanuts.jpeg"),
            },
            {
                id: "303",
                name: "MasalaNamkeen",
                price: 45,
                cutPrice: 60,
                offer: "₹15",
                qty: "1 pack",
                tag: "Indian Snacks",
                rating: "4.2 (7.3k)",
                image: require("../../assets/package snanks/namkeen.jpeg"),
            },
            {
                id: "304",
                name: "Cookies",
                price: 50,
                cutPrice: 70,
                offer: "₹20",
                qty: "1pack (100g)",
                tag: "Cookies",
                rating: "4.5 (14.6k)",
                image: require("../../assets/package snanks/cookies.jpeg"),
            },
            {
                id: "305",
                name: "Corn Puffs",
                price: 20,
                cutPrice: 35,
                offer: "₹15",
                qty: "1 pack (50g)",
                tag: "Snacks",
                rating: "4.0 (3.2k)",
                image: require("../../assets/package snanks/cornpuff.jpeg"),
            },
            {
                id: "306",
                name: "Protein Bars",
                price: 120,
                cutPrice: 150,
                offer: "₹30",
                qty: "1 bar (60g)",
                tag: "Healthy Snack",
                rating: "4.6 (8.7k)",
                image: require("../../assets/package snanks/proteinbar.jpeg"),
            },
            {
                id: "301",
                name: "Potato Chips",
                price: 35,
                cutPrice: 50,
                offer: "₹15",
                qty: "1 pack (100g)",
                tag: "Snacks",
                rating: "4.3 (12.1k)",
                image: require("../../assets/package snanks/chips.jpeg"),
            },
            {
                id: "302",
                name: "Salted Peanuts",
                price: 25,
                cutPrice: 35,
                offer: "₹10",
                qty: "1 pack",
                tag: "Snacks",
                rating: "4.1 (6.5k)",
                image: require("../../assets/package snanks/peanuts.jpeg"),
            },
            {
                id: "303",
                name: "MasalaNamkeen",
                price: 45,
                cutPrice: 60,
                offer: "₹15",
                qty: "1 pack ",
                tag: "Indian Snacks",
                rating: "4.2 (7.3k)",
                image: require("../../assets/package snanks/namkeen.jpeg"),
            },
            {
                id: "304",
                name: "Cookies",
                price: 50,
                cutPrice: 70,
                offer: "₹20",
                qty: "1 pack (100g)",
                tag: "Cookies",
                rating: "4.5 (14.6k)",
                image: require("../../assets/package snanks/cookies.jpeg"),
            },
            {
                id: "305",
                name: "Corn Puffs",
                price: 20,
                cutPrice: 35,
                offer: "₹15",
                qty: "1 pack (50g)",
                tag: "Snacks",
                rating: "4.0 (3.2k)",
                image: require("../../assets/package snanks/cornpuff.jpeg"),
            },
            {
                id: "306",
                name: "Protein Bars",
                price: 120,
                cutPrice: 150,
                offer: "₹30",
                qty: "1 bar (60g)",
                tag: "Healthy Snack",
                rating: "4.6 (8.7k)",
                image: require("../../assets/package snanks/proteinbar.jpeg"),
            },
            {
                id: "301",
                name: "Potato Chips",
                price: 35,
                cutPrice: 50,
                offer: "₹15",
                qty: "1 pack (100g)",
                tag: "Snacks",
                rating: "4.3 (12.1k)",
                image: require("../../assets/package snanks/chips.jpeg"),
            },
            {
                id: "302",
                name: "Salted Peanuts",
                price: 25,
                cutPrice: 35,
                offer: "₹10",
                qty: "1 pack",
                tag: "Snacks",
                rating: "4.1 (6.5k)",
                image: require("../../assets/package snanks/peanuts.jpeg"),
            },
            {
                id: "303",
                name: "MasalaNamkeen",
                price: 45,
                cutPrice: 60,
                offer: "₹15",
                qty: "1 pack",
                tag: "Indian Snacks",
                rating: "4.2 (7.3k)",
                image: require("../../assets/package snanks/namkeen.jpeg"),
            },
        ],
    },

    {
        id: "4",
        title: "Beverages & Drinks",
        products: [
            {
                id: "401",
                name: "Orange Juice",
                price: 60,
                cutPrice: 80,
                offer: "₹20",
                qty: "500 ml",
                tag: "Fruit Juice",
                rating: "4.4 (5.1k)",
                image: require("../../assets/drinks/orangejuice.jpeg"),
            },
            {
                id: "402",
                name: "Soft Drink",
                price: 40,
                cutPrice: 55,
                offer: "₹15",
                qty: "600 ml",
                tag: "Cold Drink",
                rating: "4.3 (12.8k)",
                image: require("../../assets/drinks/cola.jpeg"),
            },
            {
                id: "403",
                name: "Green Tea",
                price: 120,
                cutPrice: 150,
                offer: "₹30",
                qty: "25 tea bags",
                tag: "Healthy Drink",
                rating: "4.6 (9.2k)",
                image: require("../../assets/drinks/greentea.jpeg"),
            },
            {
                id: "404",
                name: "Energy Drink",
                price: 95,
                cutPrice: 120,
                offer: "₹25",
                qty: "250 ml can",
                tag: "Energy",
                rating: "4.5 (7.9k)",
                image: require("../../assets/drinks/energy.jpeg"),
            },
            {
                id: "405",
                name: "Cold Coffee",
                price: 35,
                cutPrice: 55,
                offer: "₹20",
                qty: "200 ml",
                tag: "Coffee",
                rating: "4.2 (6.7k)",
                image: require("../../assets/drinks/coldcoffee.jpeg"),
            },
            {
                id: "406",
                name: "Buttermilk",
                price: 20,
                cutPrice: 30,
                offer: "₹10",
                qty: "200 ml",
                tag: "Dairy Drink",
                rating: "4.5 (4.4k)",
                image: require("../../assets/drinks/buttermilk.jpeg"),
            },
            {
                id: "401",
                name: "Orange Juice",
                price: 60,
                cutPrice: 80,
                offer: "₹20",
                qty: "500 ml",
                tag: "Fruit Juice",
                rating: "4.4 (5.1k)",
                image: require("../../assets/drinks/orangejuice.jpeg"),
            },
            {
                id: "402",
                name: "Soft Drink ",
                price: 40,
                cutPrice: 55,
                offer: "₹15",
                qty: "600 ml",
                tag: "Cold Drink",
                rating: "4.3 (12.8k)",
                image: require("../../assets/drinks/cola.jpeg"),
            },
            {
                id: "403",
                name: "Green Tea",
                price: 120,
                cutPrice: 150,
                offer: "₹30",
                qty: "25 tea bags",
                tag: "Healthy Drink",
                rating: "4.6 (9.2k)",
                image: require("../../assets/drinks/greentea.jpeg"),
            },
            {
                id: "404",
                name: "Energy Drink",
                price: 95,
                cutPrice: 120,
                offer: "₹25",
                qty: "250 ml can",
                tag: "Energy",
                rating: "4.5 (7.9k)",
                image: require("../../assets/drinks/energy.jpeg"),
            },
            {
                id: "405",
                name: "Cold Coffee",
                price: 35,
                cutPrice: 55,
                offer: "₹20",
                qty: "200 ml",
                tag: "Coffee",
                rating: "4.2 (6.7k)",
                image: require("../../assets/drinks/coldcoffee.jpeg"),
            },
            {
                id: "406",
                name: "Buttermilk",
                price: 20,
                cutPrice: 30,
                offer: "₹10",
                qty: "200 ml",
                tag: "Dairy Drink",
                rating: "4.5 (4.4k)",
                image: require("../../assets/drinks/buttermilk.jpeg"),
            },
            {
                id: "401",
                name: "Orange Juice",
                price: 60,
                cutPrice: 80,
                offer: "₹20",
                qty: "500 ml",
                tag: "Fruit Juice",
                rating: "4.4 (5.1k)",
                image: require("../../assets/drinks/orangejuice.jpeg"),
            },
            {
                id: "402",
                name: "Soft Drink",
                price: 40,
                cutPrice: 55,
                offer: "₹15",
                qty: "600 ml",
                tag: "Cold Drink",
                rating: "4.3 (12.8k)",
                image: require("../../assets/drinks/cola.jpeg"),
            },
            {
                id: "403",
                name: "Green Tea",
                price: 120,
                cutPrice: 150,
                offer: "₹30",
                qty: "25 tea bags",
                tag: "Healthy Drink",
                rating: "4.6 (9.2k)",
                image: require("../../assets/drinks/greentea.jpeg"),
            },
        ],
    },

    {
        id: "5",
        title: "Bakery & Sweets",
        products: [
            {
                id: "501",
                name: "Cake Slice",
                price: 60,
                cutPrice: 80,
                offer: "₹20",
                qty: "1 slice",
                tag: "Bakery",
                rating: "4.7 (3.9k)",
                image: require("../../assets/dairy products/cake.jpeg"),
            },
            {
                id: "502",
                name: "Donuts",
                price: 45,
                cutPrice: 60,
                offer: "₹15",
                qty: "1 piece",
                tag: "Sweet",
                rating: "4.6 (6.1k)",
                image: require("../../assets/dairy products/donut.jpeg"),
            },
            {
                id: "503",
                name: "Rusk Toast",
                price: 35,
                cutPrice: 50,
                offer: "₹15",
                qty: "1 pack (200g)",
                tag: "Bakery",
                rating: "4.3 (5.2k)",
                image: require("../../assets/dairy products/rusk.jpeg"),
            },
            {
                id: "504",
                name: "Muffins",
                price: 55,
                cutPrice: 75,
                offer: "₹20",
                qty: "1 pack (2 pcs)",
                tag: "Sweet",
                rating: "4.5 (4.8k)",
                image: require("../../assets/dairy products/muffin.jpeg"),
            },
            {
                id: "505",
                name: "Milk Sweets ",
                price: 180,
                cutPrice: 220,
                offer: "₹40",
                qty: "500 g",
                tag: "Indian Sweets",
                rating: "4.4 (3.3k)",
                image: require("../../assets/dairy products/milksweets.jpeg"),
            },
            {
                id: "506",
                name: "Bread Rolls",
                price: 30,
                cutPrice: 40,
                offer: "₹10",
                qty: "4 pcs",
                tag: "Bakery",
                rating: "4.1 (2.9k)",
                image: require("../../assets/dairy products/rolls.jpeg"),
            },
            {
                id: "501",
                name: "Cake Slice",
                price: 60,
                cutPrice: 80,
                offer: "₹20",
                qty: "1 slice",
                tag: "Bakery",
                rating: "4.7 (3.9k)",
                image: require("../../assets/dairy products/cake.jpeg"),
            },
            {
                id: "502",
                name: "Donuts ",
                price: 45,
                cutPrice: 60,
                offer: "₹15",
                qty: "1 piece",
                tag: "Sweet",
                rating: "4.6 (6.1k)",
                image: require("../../assets/dairy products/donut.jpeg"),
            },
            {
                id: "503",
                name: "Rusk Toast",
                price: 35,
                cutPrice: 50,
                offer: "₹15",
                qty: "1 pack (200g)",
                tag: "Bakery",
                rating: "4.3 (5.2k)",
                image: require("../../assets/dairy products/rusk.jpeg"),
            },
            {
                id: "504",
                name: "Muffins",
                price: 55,
                cutPrice: 75,
                offer: "₹20",
                qty: "1 pack (2 pcs)",
                tag: "Sweet",
                rating: "4.5 (4.8k)",
                image: require("../../assets/dairy products/muffin.jpeg"),
            },
            {
                id: "505",
                name: "Milk Sweets",
                price: 180,
                cutPrice: 220,
                offer: "₹40",
                qty: "500 g",
                tag: "Indian Sweets",
                rating: "4.4 (3.3k)",
                image: require("../../assets/dairy products/milksweets.jpeg"),
            },
            {
                id: "506",
                name: "Bread Rolls",
                price: 30,
                cutPrice: 40,
                offer: "₹10",
                qty: "4 pcs",
                tag: "Bakery",
                rating: "4.1 (2.9k)",
                image: require("../../assets/dairy products/rolls.jpeg"),
            },
            {
                id: "501",
                name: "Cake Slice",
                price: 60,
                cutPrice: 80,
                offer: "₹20",
                qty: "1 slice",
                tag: "Bakery",
                rating: "4.7 (3.9k)",
                image: require("../../assets/dairy products/cake.jpeg"),
            },
            {
                id: "502",
                name: "Donuts",
                price: 45,
                cutPrice: 60,
                offer: "₹15",
                qty: "1 piece",
                tag: "Sweet",
                rating: "4.6 (6.1k)",
                image: require("../../assets/dairy products/donut.jpeg"),
            },
            {
                id: "503",
                name: "Rusk Toast",
                price: 35,
                cutPrice: 50,
                offer: "₹15",
                qty: "1 pack (200g)",
                tag: "Bakery",
                rating: "4.3 (5.2k)",
                image: require("../../assets/dairy products/rusk.jpeg"),
            },

        ],
    },

    {
        id: "6",
        title: "Grains & Pulses",
        products: [
            {
                id: "601",
                name: "Basmati Rice",
                price: 120,
                cutPrice: 140,
                offer: "₹20",
                qty: "1 kg",
                tag: "Rice",
                rating: "4.7 (14.2k)",
                image: require("../../assets/package snanks/rice.jpeg"),
            },
            {
                id: "602",
                name: "Toor Dal",
                price: 95,
                cutPrice: 120,
                offer: "₹25",
                qty: "1 kg",
                tag: "Pulse",
                rating: "4.6 (11.8k)",
                image: require("../../assets/package snanks/toordal.jpeg"),
            },
            {
                id: "603",
                name: "Wheat Flour",
                price: 55,
                cutPrice: 70,
                offer: "₹15",
                qty: "1 kg",
                tag: "Flour",
                rating: "4.5 (7.3k)",
                image: require("../../assets/package snanks/flour.jpeg"),
            },
            {
                id: "604",
                name: "Moong Dal",
                price: 90,
                cutPrice: 110,
                offer: "₹20",
                qty: "1 kg",
                tag: "Pulse",
                rating: "4.6 (8.9k)",
                image: require("../../assets/package snanks/moongdal.jpeg"),
            },
            {
                id: "605",
                name: "Brown Rice",
                price: 110,
                cutPrice: 135,
                offer: "₹25",
                qty: "1 kg",
                tag: "Healthy Grain",
                rating: "4.4 (6.5k)",
                image: require("../../assets/package snanks/brownrice.jpeg"),
            },
            {
                id: "606",
                name: "Chana Dal",
                price: 75,
                cutPrice: 90,
                offer: "₹15",
                qty: "1 kg",
                tag: "Pulse",
                rating: "4.3 (5.1k)",
                image: require("../../assets/package snanks/chanadal.jpeg"),
            },
            {
                id: "601",
                name: "Basmati Rice",
                price: 120,
                cutPrice: 140,
                offer: "₹20",
                qty: "1 kg",
                tag: "Rice",
                rating: "4.7 (14.2k)",
                image: require("../../assets/package snanks/rice.jpeg"),
            },
            {
                id: "602",
                name: "Toor Dal",
                price: 95,
                cutPrice: 120,
                offer: "₹25",
                qty: "1 kg",
                tag: "Pulse",
                rating: "4.6 (11.8k)",
                image: require("../../assets/package snanks/toordal.jpeg"),
            },
            {
                id: "603",
                name: "Wheat Flour",
                price: 55,
                cutPrice: 70,
                offer: "₹15",
                qty: "1 kg",
                tag: "Flour",
                rating: "4.5 (7.3k)",
                image: require("../../assets/package snanks/flour.jpeg"),
            },
            {
                id: "604",
                name: "Moong Dal",
                price: 90,
                cutPrice: 110,
                offer: "₹20",
                qty: "1 kg",
                tag: "Pulse",
                rating: "4.6 (8.9k)",
                image: require("../../assets/package snanks/moongdal.jpeg"),
            },
            {
                id: "605",
                name: "Brown Rice",
                price: 110,
                cutPrice: 135,
                offer: "₹25",
                qty: "1 kg",
                tag: "Healthy Grain",
                rating: "4.4 (6.5k)",
                image: require("../../assets/package snanks/brownrice.jpeg"),
            },
            {
                id: "606",
                name: "Chana Dal",
                price: 75,
                cutPrice: 90,
                offer: "₹15",
                qty: "1 kg",
                tag: "Pulse",
                rating: "4.3 (5.1k)",
                image: require("../../assets/package snanks/chanadal.jpeg"),
            },
            {
                id: "601",
                name: "Basmati Rice",
                price: 120,
                cutPrice: 140,
                offer: "₹20",
                qty: "1 kg",
                tag: "Rice",
                rating: "4.7 (14.2k)",
                image: require("../../assets/package snanks/rice.jpeg"),
            },
            {
                id: "602",
                name: "Toor Dal",
                price: 95,
                cutPrice: 120,
                offer: "₹25",
                qty: "1 kg",
                tag: "Pulse",
                rating: "4.6 (11.8k)",
                image: require("../../assets/package snanks/toordal.jpeg"),
            },
            {
                id: "603",
                name: "Wheat Flour",
                price: 55,
                cutPrice: 70,
                offer: "₹15",
                qty: "1 kg",
                tag: "Flour",
                rating: "4.5 (7.3k)",
                image: require("../../assets/package snanks/flour.jpeg"),
            },
        ],
    },

    {
        id: "7",
        title: "Meat, Fish & Poultry",
        products: [
            {
                id: "701",
                name: "Chicken Breast",
                price: 160,
                cutPrice: 190,
                offer: "₹30",
                qty: "500 g",
                tag: "Fresh Chicken",
                rating: "4.7 (9.8k)",
                image: require("../../assets/dairy products/chickenbreast.jpeg"),
            },
            {
                id: "702",
                name: "Mutton Curry Cut",
                price: 380,
                cutPrice: 450,
                offer: "₹70",
                qty: "500 g",
                tag: "Meat",
                rating: "4.6 (7.1k)",
                image: require("../../assets/dairy products/mutton.jpeg"),
            },
            {
                id: "703",
                name: "Fish Fillets",
                price: 220,
                cutPrice: 260,
                offer: "₹40",
                qty: "500 g",
                tag: "Seafood",
                rating: "4.5 (5.9k)",
                image: require("../../assets/dairy products/fish.jpeg"),
            },
            {
                id: "704",
                name: "Prawns",
                price: 300,
                cutPrice: 350,
                offer: "₹50",
                qty: "500 g",
                tag: "Seafood",
                rating: "4.6 (4.2k)",
                image: require("../../assets/dairy products/pranws.jpeg"),
            },
            {
                id: "705",
                name: "Drumsticks",
                price: 180,
                cutPrice: 220,
                offer: "₹40",
                qty: "500 g",
                tag: "Chicken",
                rating: "4.5 (6.8k)",
                image: require("../../assets/dairy products/drumsticks.jpeg"),
            },
            {
                id: "703",
                name: "Fish Fillets",
                price: 220,
                cutPrice: 260,
                offer: "₹40",
                qty: "500 g",
                tag: "Seafood",
                rating: "4.5 (5.9k)",
                image: require("../../assets/dairy products/fish.jpeg"),
            },
            {
                id: "704",
                name: "Prawns",
                price: 300,
                cutPrice: 350,
                offer: "₹50",
                qty: "500 g",
                tag: "Seafood",
                rating: "4.6 (4.2k)",
                image: require("../../assets/dairy products/pranws.jpeg"),
            },
            {
                id: "701",
                name: "Chicken Breast",
                price: 160,
                cutPrice: 190,
                offer: "₹30",
                qty: "500 g",
                tag: "Fresh Chicken",
                rating: "4.7 (9.8k)",
                image: require("../../assets/dairy products/chickenbreast.jpeg"),
            },
            {
                id: "702",
                name: "Mutton Curry Cut",
                price: 380,
                cutPrice: 450,
                offer: "₹70",
                qty: "500 g",
                tag: "Meat",
                rating: "4.6 (7.1k)",
                image: require("../../assets/dairy products/mutton.jpeg"),
            },
            {
                id: "703",
                name: "Fish Fillets",
                price: 220,
                cutPrice: 260,
                offer: "₹40",
                qty: "500 g",
                tag: "Seafood",
                rating: "4.5 (5.9k)",
                image: require("../../assets/dairy products/fish.jpeg"),
            },
            {
                id: "704",
                name: "Prawns",
                price: 300,
                cutPrice: 350,
                offer: "₹50",
                qty: "500 g",
                tag: "Seafood",
                rating: "4.6 (4.2k)",
                image: require("../../assets/dairy products/pranws.jpeg"),
            },
            {
                id: "705",
                name: "Drumsticks",
                price: 180,
                cutPrice: 220,
                offer: "₹40",
                qty: "500 g",
                tag: "Chicken",
                rating: "4.5 (6.8k)",
                image: require("../../assets/dairy products/drumsticks.jpeg"),
            },
            {
                id: "701",
                name: "Chicken Breast",
                price: 160,
                cutPrice: 190,
                offer: "₹30",
                qty: "500 g",
                tag: "Fresh Chicken",
                rating: "4.7 (9.8k)",
                image: require("../../assets/dairy products/chickenbreast.jpeg"),
            },
            {
                id: "702",
                name: "Mutton Curry Cut",
                price: 380,
                cutPrice: 450,
                offer: "₹70",
                qty: "500 g",
                tag: "Meat",
                rating: "4.6 (7.1k)",
                image: require("../../assets/dairy products/mutton.jpeg"),
            },
            {
                id: "703",
                name: "Fish Fillets",
                price: 220,
                cutPrice: 260,
                offer: "₹40",
                qty: "500 g",
                tag: "Seafood",
                rating: "4.5 (5.9k)",
                image: require("../../assets/dairy products/fish.jpeg"),
            },

        ],
    },

    {
        id: "8",
        title: "Frozen Foods",
        products: [
            {
                id: "801",
                name: "Veg Momos",
                price: 120,
                cutPrice: 150,
                offer: "₹30",
                qty: "20 pieces",
                tag: "Frozen Snacks",
                rating: "4.5 (9.1k)",
                image: require("../../assets/package snanks/momos.jpeg"),
            },
            {
                id: "802",
                name: "Frozen French Fries",
                price: 95,
                cutPrice: 120,
                offer: "₹25",
                qty: "750 g",
                tag: "Frozen",
                rating: "4.6 (10.3k)",
                image: require("../../assets/package snanks/fries.jpeg"),
            },
            {
                id: "803",
                name: "Chicken Nuggets",
                price: 180,
                cutPrice: 220,
                offer: "₹40",
                qty: "500 g",
                tag: "Chicken",
                rating: "4.4 (7.9k)",
                image: require("../../assets/package snanks/nuggets.jpeg"),
            },
            {
                id: "804",
                name: "Mixed Veg Pack",
                price: 110,
                cutPrice: 140,
                offer: "₹30",
                qty: "500 g",
                tag: "Frozen Veg",
                rating: "4.5 (6.2k)",
                image: require("../../assets/package snanks/veg.jpeg"),
            },
            {
                id: "805",
                name: "Ice Cream Tub",
                price: 150,
                cutPrice: 180,
                offer: "₹30",
                qty: "500 ml",
                tag: "Dessert",
                rating: "4.8 (14.5k)",
                image: require("../../assets/package snanks/icecream.jpeg"),
            },
            {
                id: "806",
                name: "Frozen Paratha",
                price: 90,
                cutPrice: 120,
                offer: "₹30",
                qty: "5 pieces",
                tag: "Indian Food",
                rating: "4.4 (3.7k)",
                image: require("../../assets/package snanks/paratha.jpeg"),
            },
            {
                id: "801",
                name: "Veg Momos",
                price: 120,
                cutPrice: 150,
                offer: "₹30",
                qty: "20 pieces",
                tag: "Frozen Snacks",
                rating: "4.5 (9.1k)",
                image: require("../../assets/package snanks/momos.jpeg"),
            },
            {
                id: "802",
                name: "Frozen French Fries",
                price: 95,
                cutPrice: 120,
                offer: "₹25",
                qty: "750 g",
                tag: "Frozen",
                rating: "4.6 (10.3k)",
                image: require("../../assets/package snanks/fries.jpeg"),
            },
            {
                id: "803",
                name: "Chicken Nuggets",
                price: 180,
                cutPrice: 220,
                offer: "₹40",
                qty: "500 g",
                tag: "Chicken",
                rating: "4.4 (7.9k)",
                image: require("../../assets/package snanks/nuggets.jpeg"),
            },
            {
                id: "804",
                name: "Mixed Veg Pack",
                price: 110,
                cutPrice: 140,
                offer: "₹30",
                qty: "500 g",
                tag: "Frozen Veg",
                rating: "4.5 (6.2k)",
                image: require("../../assets/package snanks/veg.jpeg"),
            },
            {
                id: "805",
                name: "Ice Cream Tub",
                price: 150,
                cutPrice: 180,
                offer: "₹30",
                qty: "500 ml",
                tag: "Dessert",
                rating: "4.8 (14.5k)",
                image: require("../../assets/package snanks/icecream.jpeg"),
            },
            {
                id: "806",
                name: "Frozen Paratha",
                price: 90,
                cutPrice: 120,
                offer: "₹30",
                qty: "5 pieces",
                tag: "Indian Food",
                rating: "4.4 (3.7k)",
                image: require("../../assets/package snanks/paratha.jpeg"),
            },
            {
                id: "801",
                name: "Veg Momos",
                price: 120,
                cutPrice: 150,
                offer: "₹30",
                qty: "20 pieces",
                tag: "Frozen Snacks",
                rating: "4.5 (9.1k)",
                image: require("../../assets/package snanks/momos.jpeg"),
            },
            {
                id: "802",
                name: "Frozen French Fries",
                price: 95,
                cutPrice: 120,
                offer: "₹25",
                qty: "750 g",
                tag: "Frozen",
                rating: "4.6 (10.3k)",
                image: require("../../assets/package snanks/fries.jpeg"),
            },
            {
                id: "803",
                name: "Chicken Nuggets",
                price: 180,
                cutPrice: 220,
                offer: "₹40",
                qty: "500 g",
                tag: "Chicken",
                rating: "4.4 (7.9k)",
                image: require("../../assets/package snanks/nuggets.jpeg"),
            },
        ],
    },

    {
        id: "9",
        title: "Fashion & Styles",
        products: [
            {
                id: "901",
                name: "Men's T-Shirt",
                price: 399,
                cutPrice: 599,
                offer: "₹200",
                qty: "1 piece",
                tag: "Men Clothing",
                rating: "4.5 (11.1k)",
                image: require("../../assets/fashion/tshirt.jpeg"),
            },
            {
                id: "902",
                name: "Women's Kurti",
                price: 499,
                cutPrice: 799,
                offer: "₹300",
                qty: "1 piece",
                tag: "Women",
                rating: "4.6 (8.7k)",
                image: require("../../assets/fashion/kurti.jpeg"),
            },
            {
                id: "903",
                name: "Jeans ",
                price: 899,
                cutPrice: 1299,
                offer: "₹400",
                qty: "1 piece",
                tag: "Bottom Wear",
                rating: "4.4 (6.8k)",
                image: require("../../assets/fashion/jeans.jpeg"),
            },
            {
                id: "904",
                name: "Sneakers",
                price: 1199,
                cutPrice: 1699,
                offer: "₹50",
                qty: "1 pair",
                tag: "Footwear",
                rating: "4.6 (10.3k)",
                image: require("../../assets/fashion/shoes.jpeg"),
            },
            {
                id: "905",
                name: "Hoodie",
                price: 699,
                cutPrice: 999,
                offer: "₹300",
                qty: "1 piece",
                tag: "Winter Wear",
                rating: "4.5 (7.2k)",
                image: require("../../assets/fashion/hoodie.jpeg"),
            },
            {
                id: "906",
                name: "Sunglasses",
                price: 299,
                cutPrice: 499,
                offer: "₹200",
                qty: "1 piece",
                tag: "Accessories",
                rating: "4.4 (5.1k)",
                image: require("../../assets/fashion/sunglasses.jpeg"),
            },
            {
                id: "901",
                name: "Men's T-Shirt",
                price: 399,
                cutPrice: 599,
                offer: "₹200",
                qty: "1 piece",
                tag: "Men Clothing",
                rating: "4.5 (11.1k)",
                image: require("../../assets/fashion/tshirt.jpeg"),
            },
            {
                id: "902",
                name: "Women's Kurti",
                price: 499,
                cutPrice: 799,
                offer: "₹300",
                qty: "1 piece",
                tag: "Women",
                rating: "4.6 (8.7k)",
                image: require("../../assets/fashion/kurti.jpeg"),
            },
            {
                id: "903",
                name: "Jeans (Slim Fit)",
                price: 899,
                cutPrice: 1299,
                offer: "₹400",
                qty: "1 piece",
                tag: "Bottom Wear",
                rating: "4.4 (6.8k)",
                image: require("../../assets/fashion/jeans.jpeg"),
            },
            {
                id: "904",
                name: "Sneakers",
                price: 1199,
                cutPrice: 1699,
                offer: "₹50",
                qty: "1 pair",
                tag: "Footwear",
                rating: "4.6 (10.3k)",
                image: require("../../assets/fashion/shoes.jpeg"),
            },
            {
                id: "905",
                name: "Hoodie",
                price: 699,
                cutPrice: 999,
                offer: "₹300",
                qty: "1 piece",
                tag: "Winter Wear",
                rating: "4.5 (7.2k)",
                image: require("../../assets/fashion/hoodie.jpeg"),
            },
            {
                id: "906",
                name: "Sunglasses",
                price: 299,
                cutPrice: 499,
                offer: "₹200",
                qty: "1 piece",
                tag: "Accessories",
                rating: "4.4 (5.1k)",
                image: require("../../assets/fashion/sunglasses.jpeg"),
            },
            {
                id: "901",
                name: "Men's T-Shirt",
                price: 399,
                cutPrice: 599,
                offer: "₹200",
                qty: "1 piece",
                tag: "Men Clothing",
                rating: "4.5 (11.1k)",
                image: require("../../assets/fashion/tshirt.jpeg"),
            },
            {
                id: "902",
                name: "Women's Kurti",
                price: 499,
                cutPrice: 799,
                offer: "₹300",
                qty: "1 piece",
                tag: "Women",
                rating: "4.6 (8.7k)",
                image: require("../../assets/fashion/kurti.jpeg"),
            },
            {
                id: "903",
                name: "Jeans ",
                price: 899,
                cutPrice: 1299,
                offer: "₹400",
                qty: "1 piece",
                tag: "Bottom Wear",
                rating: "4.4 (6.8k)",
                image: require("../../assets/fashion/jeans.jpeg"),
            },
        ],
    },

    {
        id: "10",
        title: "Makeup & Beauty",
        products: [
            {
                id: "1001",
                name: "Lipstick (Matte)",
                price: 199,
                cutPrice: 299,
                offer: "₹100",
                qty: "1 piece",
                tag: "Makeup",
                rating: "4.6 (12.2k)",
                image: require("../../assets/fashion/lipstick.jpeg"),
            },
            {
                id: "1002",
                name: "Foundation",
                price: 349,
                cutPrice: 499,
                offer: "₹150",
                qty: "1 bottle",
                tag: "Makeup",
                rating: "4.5 (9.8k)",
                image: require("../../assets/fashion/foundation.jpeg"),
            },
            {
                id: "1003",
                name: "Mascara",
                price: 249,
                cutPrice: 350,
                offer: "₹101",
                qty: "1 piece",
                tag: "Eye Makeup",
                rating: "4.7 (8.1k)",
                image: require("../../assets/fashion/maskara.jpeg"),
            },
            {
                id: "1004",
                name: "Makeup Brushes",
                price: 499,
                cutPrice: 699,
                offer: "₹200",
                qty: "6 pcs set",
                tag: "Tools",
                rating: "4.6 (4.9k)",
                image: require("../../assets/fashion/brushs.jpeg"),
            },
            {
                id: "1005",
                name: "Compact Powder",
                price: 199,
                cutPrice: 260,
                offer: "₹61",
                qty: "1 piece",
                tag: "Face Makeup",
                rating: "4.4 (6.6k)",
                image: require("../../assets/fashion/compact.jpeg"),
            },
            {
                id: "1006",
                name: "Nail Polish",
                price: 99,
                cutPrice: 150,
                offer: "₹51",
                qty: "1 bottle",
                tag: "Nail",
                rating: "4.3 (5.4k)",
                image: require("../../assets/fashion/nailpolish.jpeg"),
            },
            {
                id: "1001",
                name: "Lipstick (Matte)",
                price: 199,
                cutPrice: 299,
                offer: "₹100",
                qty: "1 piece",
                tag: "Makeup",
                rating: "4.6 (12.2k)",
                image: require("../../assets/fashion/lipstick.jpeg"),
            },
            {
                id: "1002",
                name: "Foundation",
                price: 349,
                cutPrice: 499,
                offer: "₹150",
                qty: "1 bottle",
                tag: "Makeup",
                rating: "4.5 (9.8k)",
                image: require("../../assets/fashion/foundation.jpeg"),
            },
            {
                id: "1003",
                name: "Mascara",
                price: 249,
                cutPrice: 350,
                offer: "₹101",
                qty: "1 piece",
                tag: "Eye Makeup",
                rating: "4.7 (8.1k)",
                image: require("../../assets/fashion/maskara.jpeg"),
            },
            {
                id: "1004",
                name: "Makeup Brushes",
                price: 499,
                cutPrice: 699,
                offer: "₹200",
                qty: "6 pcs set",
                tag: "Tools",
                rating: "4.6 (4.9k)",
                image: require("../../assets/fashion/brushs.jpeg"),
            },
            {
                id: "1005",
                name: "Compact Powder",
                price: 199,
                cutPrice: 260,
                offer: "₹61",
                qty: "1 piece",
                tag: "Face Makeup",
                rating: "4.4 (6.6k)",
                image: require("../../assets/fashion/compact.jpeg"),
            },
            {
                id: "1006",
                name: "Nail Polish",
                price: 99,
                cutPrice: 150,
                offer: "₹51",
                qty: "1 bottle",
                tag: "Nail",
                rating: "4.3 (5.4k)",
                image: require("../../assets/fashion/nailpolish.jpeg"),
            },
            {
                id: "1001",
                name: "Lipstick (Matte)",
                price: 199,
                cutPrice: 299,
                offer: "₹100",
                qty: "1 piece",
                tag: "Makeup",
                rating: "4.6 (12.2k)",
                image: require("../../assets/fashion/lipstick.jpeg"),
            },
            {
                id: "1002",
                name: "Foundation",
                price: 349,
                cutPrice: 499,
                offer: "₹150",
                qty: "1 bottle",
                tag: "Makeup",
                rating: "4.5 (9.8k)",
                image: require("../../assets/fashion/foundation.jpeg"),
            },
            {
                id: "1003",
                name: "Mascara",
                price: 249,
                cutPrice: 350,
                offer: "₹101",
                qty: "1 piece",
                tag: "Eye Makeup",
                rating: "4.7 (8.1k)",
                image: require("../../assets/fashion/maskara.jpeg"),
            },

        ],
    },

    {
        id: "11",
        title: "Skincare & Haircare",
        products: [
            {
                id: "1101",
                name: "Aloe Vera Gel",
                price: 120,
                cutPrice: 160,
                offer: "₹40",
                qty: "150 g",
                tag: "Skincare",
                rating: "4.7 (14.6k)",
                image: require("../../assets/fashion/aloe.jpeg"),
            },
            {
                id: "1102",
                name: "Face Wash",
                price: 150,
                cutPrice: 180,
                offer: "₹30",
                qty: "100 ml",
                tag: "Skincare",
                rating: "4.5 (9.1k)",
                image: require("../../assets/fashion/facewash.jpeg"),
            },
            {
                id: "1103",
                name: "Shampoo",
                price: 210,
                cutPrice: 260,
                offer: "₹50",
                qty: "180 ml",
                tag: "Haircare",
                rating: "4.6 (11.3k)",
                image: require("../../assets/fashion/shampoo.jpeg"),
            },
            {
                id: "1104",
                name: "Conditioner",
                price: 190,
                cutPrice: 230,
                offer: "₹40",
                qty: "150 ml",
                tag: "Haircare",
                rating: "4.6 (7.7k)",
                image: require("../../assets/fashion/conditioner.jpeg"),
            },
            {
                id: "1105",
                name: "Moisturizer",
                price: 220,
                cutPrice: 270,
                offer: "₹50",
                qty: "200 ml",
                tag: "Skincare",
                rating: "4.5 (10.5k)",
                image: require("../../assets/fashion/moisturizer.jpeg"),
            },
            {
                id: "1106",
                name: "Hair Oil",
                price: 120,
                cutPrice: 160,
                offer: "₹40",
                qty: "200 ml",
                tag: "Haircare",
                rating: "4.4 (8.2k)",
                image: require("../../assets/fashion/hairoil.jpeg"),
            },
            {
                id: "1101",
                name: "Aloe Vera Gel",
                price: 120,
                cutPrice: 160,
                offer: "₹40",
                qty: "150 g",
                tag: "Skincare",
                rating: "4.7 (14.6k)",
                image: require("../../assets/fashion/aloe.jpeg"),
            },
            {
                id: "1102",
                name: "Face Wash",
                price: 150,
                cutPrice: 180,
                offer: "₹30",
                qty: "100 ml",
                tag: "Skincare",
                rating: "4.5 (9.1k)",
                image: require("../../assets/fashion/facewash.jpeg"),
            },
            {
                id: "1103",
                name: "Shampoo",
                price: 210,
                cutPrice: 260,
                offer: "₹50",
                qty: "180 ml",
                tag: "Haircare",
                rating: "4.6 (11.3k)",
                image: require("../../assets/fashion/shampoo.jpeg"),
            },
            {
                id: "1104",
                name: "Conditioner",
                price: 190,
                cutPrice: 230,
                offer: "₹40",
                qty: "150 ml",
                tag: "Haircare",
                rating: "4.6 (7.7k)",
                image: require("../../assets/fashion/conditioner.jpeg"),
            },
            {
                id: "1105",
                name: "Moisturizer",
                price: 220,
                cutPrice: 270,
                offer: "₹50",
                qty: "200 ml",
                tag: "Skincare",
                rating: "4.5 (10.5k)",
                image: require("../../assets/fashion/moisturizer.jpeg"),
            },
            {
                id: "1106",
                name: "Hair Oil",
                price: 120,
                cutPrice: 160,
                offer: "₹40",
                qty: "200 ml",
                tag: "Haircare",
                rating: "4.4 (8.2k)",
                image: require("../../assets/fashion/hairoil.jpeg"),
            },
            {
                id: "1101",
                name: "Aloe Vera Gel",
                price: 120,
                cutPrice: 160,
                offer: "₹40",
                qty: "150 g",
                tag: "Skincare",
                rating: "4.7 (14.6k)",
                image: require("../../assets/fashion/aloe.jpeg"),
            },
            {
                id: "1102",
                name: "Face Wash",
                price: 150,
                cutPrice: 180,
                offer: "₹30",
                qty: "100 ml",
                tag: "Skincare",
                rating: "4.5 (9.1k)",
                image: require("../../assets/fashion/facewash.jpeg"),
            },
            {
                id: "1103",
                name: "Shampoo",
                price: 210,
                cutPrice: 260,
                offer: "₹50",
                qty: "180 ml",
                tag: "Haircare",
                rating: "4.6 (11.3k)",
                image: require("../../assets/fashion/shampoo.jpeg"),
            },
        ],
    },

    {
        id: "12",
        title: "Stationery & Office Supplies",
        products: [
            {
                id: "1201",
                name: "Ball Pens ",
                price: 50,
                cutPrice: 70,
                offer: "₹20",
                qty: "10 pcs",
                tag: "Stationery",
                rating: "4.5 (6.9k)",
                image: require("../../assets/supplies/pens.jpeg"),
            },
            {
                id: "1202",
                name: "Notebook",
                price: 60,
                cutPrice: 80,
                offer: "₹20",
                qty: "200 pages",
                tag: "Office",
                rating: "4.4 (5.3k)",
                image: require("../../assets/supplies/notebook.jpeg"),
            },
            {
                id: "1203",
                name: "Highlighters",
                price: 120,
                cutPrice: 150,
                offer: "₹30",
                qty: "Set of 5",
                tag: "Stationery",
                rating: "4.6 (4.8k)",
                image: require("../../assets/supplies/highlighters.jpeg"),
            },
            {
                id: "1204",
                name: "A4 Printing Paper",
                price: 290,
                cutPrice: 330,
                offer: "₹40",
                qty: "1 ream",
                tag: "Office Supplies",
                rating: "4.7 (9.2k)",
                image: require("../../assets/supplies/a4.jpeg"),
            },
            {
                id: "1205",
                name: "Sticky Notes",
                price: 45,
                cutPrice: 60,
                offer: "₹15",
                qty: "100 sheets",
                tag: "Office",
                rating: "4.5 (3.1k)",
                image: require("../../assets/supplies/stickynotes.jpeg"),
            },
            {
                id: "1206",
                name: "Markers",
                price: 110,
                cutPrice: 140,
                offer: "₹30",
                qty: "Pack of 4",
                tag: "Office",
                rating: "4.6 (4k)",
                image: require("../../assets/supplies/markers.jpeg"),
            },
            {
                id: "1201",
                name: "Ball Pens ",
                price: 50,
                cutPrice: 70,
                offer: "₹20",
                qty: "10 pcs",
                tag: "Stationery",
                rating: "4.5 (6.9k)",
                image: require("../../assets/supplies/pens.jpeg"),
            },
            {
                id: "1202",
                name: "Notebook",
                price: 60,
                cutPrice: 80,
                offer: "₹20",
                qty: "200 pages",
                tag: "Office",
                rating: "4.4 (5.3k)",
                image: require("../../assets/supplies/notebook.jpeg"),
            },
            {
                id: "1203",
                name: "Highlighters",
                price: 120,
                cutPrice: 150,
                offer: "₹30",
                qty: "Set of 5",
                tag: "Stationery",
                rating: "4.6 (4.8k)",
                image: require("../../assets/supplies/highlighters.jpeg"),
            },
            {
                id: "1204",
                name: "A4 Printing Paper",
                price: 290,
                cutPrice: 330,
                offer: "₹40",
                qty: "1 ream",
                tag: "Office Supplies",
                rating: "4.7 (9.2k)",
                image: require("../../assets/supplies/a4.jpeg"),
            },
            {
                id: "1205",
                name: "Sticky Notes",
                price: 45,
                cutPrice: 60,
                offer: "₹15",
                qty: "100 sheets",
                tag: "Office",
                rating: "4.5 (3.1k)",
                image: require("../../assets/supplies/stickynotes.jpeg"),
            },
            {
                id: "1206",
                name: "Markers",
                price: 110,
                cutPrice: 140,
                offer: "₹30",
                qty: "Pack of 4",
                tag: "Office",
                rating: "4.6 (4k)",
                image: require("../../assets/supplies/markers.jpeg"),
            },
            {
                id: "1201",
                name: "Ball Pens ",
                price: 50,
                cutPrice: 70,
                offer: "₹20",
                qty: "10 pcs",
                tag: "Stationery",
                rating: "4.5 (6.9k)",
                image: require("../../assets/supplies/pens.jpeg"),
            },
            {
                id: "1202",
                name: "Notebook",
                price: 60,
                cutPrice: 80,
                offer: "₹20",
                qty: "200 pages",
                tag: "Office",
                rating: "4.4 (5.3k)",
                image: require("../../assets/supplies/notebook.jpeg"),
            },
            {
                id: "1203",
                name: "Highlighters",
                price: 120,
                cutPrice: 150,
                offer: "₹30",
                qty: "Set of 5",
                tag: "Stationery",
                rating: "4.6 (4.8k)",
                image: require("../../assets/supplies/highlighters.jpeg"),
            },
        ],
    },

    {
        id: "13",
        title: "Kitchen & Dining",
        products: [
            {
                id: "1301",
                name: "Steel Plate",
                price: 180,
                cutPrice: 230,
                offer: "₹50",
                qty: "1 piece",
                tag: "Kitchenware",
                rating: "4.5 (7.1k)",
                image: require("../../assets/supplies/plate.jpeg"),
            },
            {
                id: "1302",
                name: "Non Stick Pan",
                price: 650,
                cutPrice: 820,
                offer: "₹170",
                qty: "1 piece",
                tag: "Cookware",
                rating: "4.6 (5.9k)",
                image: require("../../assets/supplies/pan.jpeg"),
            },
            {
                id: "1303",
                name: "Glass Set",
                price: 240,
                cutPrice: 300,
                offer: "₹60",
                qty: "6 pieces",
                tag: "Dining",
                rating: "4.4 (8.1k)",
                image: require("../../assets/supplies/glass.jpeg"),
            },
            {
                id: "1304",
                name: "Knife Set",
                price: 350,
                cutPrice: 420,
                offer: "₹70",
                qty: "3 pcs",
                tag: "Kitchen Tool",
                rating: "4.6 (3.7k)",
                image: require("../../assets/supplies/knives.jpeg"),
            },
            {
                id: "1305",
                name: "Cutting Board",
                price: 160,
                cutPrice: 210,
                offer: "₹50",
                qty: "1 piece",
                tag: "Kitchen Tool",
                rating: "4.5 (4.4k)",
                image: require("../../assets/supplies/board.jpeg"),
            },
            {
                id: "1306",
                name: "Water Bottle",
                price: 120,
                cutPrice: 160,
                offer: "₹40",
                qty: "1 piece",
                tag: "Kitchen",
                rating: "4.3 (3.3k)",
                image: require("../../assets/supplies/bottle.jpeg"),
            },
            {
                id: "1301",
                name: "Steel Plate",
                price: 180,
                cutPrice: 230,
                offer: "₹50",
                qty: "1 piece",
                tag: "Kitchenware",
                rating: "4.5 (7.1k)",
                image: require("../../assets/supplies/plate.jpeg"),
            },
            {
                id: "1302",
                name: "Non Stick Pan",
                price: 650,
                cutPrice: 820,
                offer: "₹170",
                qty: "1 piece",
                tag: "Cookware",
                rating: "4.6 (5.9k)",
                image: require("../../assets/supplies/pan.jpeg"),
            },
            {
                id: "1303",
                name: "Glass Set",
                price: 240,
                cutPrice: 300,
                offer: "₹60",
                qty: "6 pieces",
                tag: "Dining",
                rating: "4.4 (8.1k)",
                image: require("../../assets/supplies/glass.jpeg"),
            },
            {
                id: "1304",
                name: "Knife Set",
                price: 350,
                cutPrice: 420,
                offer: "₹70",
                qty: "3 pcs",
                tag: "Kitchen Tool",
                rating: "4.6 (3.7k)",
                image: require("../../assets/supplies/knives.jpeg"),
            },
            {
                id: "1305",
                name: "Cutting Board",
                price: 160,
                cutPrice: 210,
                offer: "₹50",
                qty: "1 piece",
                tag: "Kitchen Tool",
                rating: "4.5 (4.4k)",
                image: require("../../assets/supplies/board.jpeg"),
            },
            {
                id: "1306",
                name: "Water Bottle",
                price: 120,
                cutPrice: 160,
                offer: "₹40",
                qty: "1 piece",
                tag: "Kitchen",
                rating: "4.3 (3.3k)",
                image: require("../../assets/supplies/bottle.jpeg"),
            },
            {
                id: "1301",
                name: "Steel Plate",
                price: 180,
                cutPrice: 230,
                offer: "₹50",
                qty: "1 piece",
                tag: "Kitchenware",
                rating: "4.5 (7.1k)",
                image: require("../../assets/supplies/plate.jpeg"),
            },
            {
                id: "1302",
                name: "Non Stick Pan",
                price: 650,
                cutPrice: 820,
                offer: "₹170",
                qty: "1 piece",
                tag: "Cookware",
                rating: "4.6 (5.9k)",
                image: require("../../assets/supplies/pan.jpeg"),
            },
            {
                id: "1303",
                name: "Glass Set",
                price: 240,
                cutPrice: 300,
                offer: "₹60",
                qty: "6 pieces",
                tag: "Dining",
                rating: "4.4 (8.1k)",
                image: require("../../assets/supplies/glass.jpeg"),
            },
        ],
    },

    {
        id: "14",
        title: "Electronics Appliances",
        products: [
            {
                id: "1401",
                name: "Electric Kettle",
                price: 799,
                cutPrice: 999,
                offer: "₹200",
                qty: "1 piece",
                tag: "Appliance",
                rating: "4.5 (13.4k)",
                image: require("../../assets/supplies/kettle.jpeg"),
            },
            {
                id: "1402",
                name: "Mixer Grinder",
                price: 1899,
                cutPrice: 239,
                offer: "₹500",
                qty: "1 unit",
                tag: "Kitchen ",
                rating: "4.6 (7.9k)",
                image: require("../../assets/supplies/mixer.jpeg"),
            },
            {
                id: "1403",
                name: "Speaker",
                price: 999,
                cutPrice: 1499,
                offer: "₹500",
                qty: "1 piece",
                tag: "Audio",
                rating: "4.7 (18.7k)",
                image: require("../../assets/supplies/speaker.jpeg"),
            },
            {
                id: "1404",
                name: "LED Bulb",
                price: 120,
                cutPrice: 180,
                offer: "₹60",
                qty: "9W",
                tag: "Home",
                rating: "4.4 (6.2k)",
                image: require("../../assets/supplies/bulb.jpeg"),
            },
            {
                id: "1405",
                name: "Power Bank",
                price: 699,
                cutPrice: 999,
                offer: "₹300",
                qty: "10000 mAh",
                tag: "Mobile ",
                rating: "4.6 (9.4k)",
                image: require("../../assets/supplies/powerbank.jpeg"),
            },
            {
                id: "1406",
                name: "Wired Earphones",
                price: 199,
                cutPrice: 299,
                offer: "₹100",
                qty: "1 pair",
                tag: "Audio",
                rating: "4.3 (4.3k)",
                image: require("../../assets/supplies/earphones.jpeg"),
            },
            {
                id: "1401",
                name: "Electric Kettle",
                price: 799,
                cutPrice: 999,
                offer: "₹200",
                qty: "1 piece",
                tag: "Appliance",
                rating: "4.5 (13.4k)",
                image: require("../../assets/supplies/kettle.jpeg"),
            },
            {
                id: "1402",
                name: "Mixer Grinder",
                price: 1899,
                cutPrice: 239,
                offer: "₹500",
                qty: "1 unit",
                tag: "Kitchen ",
                rating: "4.6 (7.9k)",
                image: require("../../assets/supplies/mixer.jpeg"),
            },
            {
                id: "1403",
                name: "Speaker",
                price: 999,
                cutPrice: 1499,
                offer: "₹500",
                qty: "1 piece",
                tag: "Audio",
                rating: "4.7 (18.7k)",
                image: require("../../assets/supplies/speaker.jpeg"),
            },
            {
                id: "1404",
                name: "LED Bulb",
                price: 120,
                cutPrice: 180,
                offer: "₹60",
                qty: "9W",
                tag: "Home",
                rating: "4.4 (6.2k)",
                image: require("../../assets/supplies/bulb.jpeg"),
            },
            {
                id: "1405",
                name: "Power Bank",
                price: 699,
                cutPrice: 999,
                offer: "₹300",
                qty: "10000 mAh",
                tag: "Mobile ",
                rating: "4.6 (9.4k)",
                image: require("../../assets/supplies/powerbank.jpeg"),
            },
            {
                id: "1406",
                name: "Wired Earphones",
                price: 199,
                cutPrice: 299,
                offer: "₹100",
                qty: "1 pair",
                tag: "Audio",
                rating: "4.3 (4.3k)",
                image: require("../../assets/supplies/earphones.jpeg"),
            },
            {
                id: "1401",
                name: "Electric Kettle",
                price: 799,
                cutPrice: 999,
                offer: "₹200",
                qty: "1 piece",
                tag: "Appliance",
                rating: "4.5 (13.4k)",
                image: require("../../assets/supplies/kettle.jpeg"),
            },
            {
                id: "1402",
                name: "Mixer Grinder",
                price: 1899,
                cutPrice: 239,
                offer: "₹500",
                qty: "1 unit",
                tag: "Kitchen ",
                rating: "4.6 (7.9k)",
                image: require("../../assets/supplies/mixer.jpeg"),
            },
            {
                id: "1403",
                name: "Speaker",
                price: 999,
                cutPrice: 1499,
                offer: "₹500",
                qty: "1 piece",
                tag: "Audio",
                rating: "4.7 (18.7k)",
                image: require("../../assets/supplies/speaker.jpeg"),
            },

        ],
    },



];

